In [1]:
import pandas as pd

data = {
    "height": [165, 172, None, 180, 158, 175],
    "weight": [55, 70, 65, 80, 50, 68],
    "age": [25, 30, 28, 35, 22, 29],
    "gender": ["F", "M", "M", "M", "F", "M"],
}

df = pd.DataFrame(data)

In [2]:
print(df.head())

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
2     NaN      65   28      M
3   180.0      80   35      M
4   158.0      50   22      F

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  5 non-null      float64
 1   weight  6 non-null      int64
 2   age     6 non-null      int64
 3   gender  6 non-null      str
dtypes: float64(1), int64(2), str(1)
memory usage: 330.0 bytes

In [4]:
df.describe()

           height     weight        age
count    5.000000   6.000000   6.000000
mean   170.000000  64.666667  28.166667
std      8.631338  10.801234   4.445972
min    158.000000  50.000000  22.000000
25%    165.000000  57.500000  25.750000
50%    172.000000  66.500000  28.500000
75%    175.000000  69.500000  29.750000
max    180.000000  80.000000  35.000000

In [10]:
print(df.isnull().sum()) # 결측치 개수

height    1
weight    0
age       0
gender    0
dtype: int64

In [7]:
# 결측치가 있는 행 제거
df2 = df.dropna()

In [8]:
df2

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
3   180.0      80   35      M
4   158.0      50   22      F
5   175.0      68   29      M

In [9]:
# 결측치 채우기 --> fillna()
# 숫자형 --> 평균값으로 채우기
df['height'].fillna(df['height'].mean())

0    165.0
1    172.0
2    170.0
3    180.0
4    158.0
5    175.0
Name: height, dtype: float64

In [12]:
df3 = df.copy() # df복사 -> df3fh

In [13]:
df3['height'] = df['height'].fillna(df['height'].mean())

In [14]:
df3

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
2   170.0      65   28      M
3   180.0      80   35      M
4   158.0      50   22      F
5   175.0      68   29      M

In [15]:
# 결측치 채우기 --> fillna()
# 범주형 결측치를 최빈값으로 채우기 
df['gender'].mode()

0    M
Name: gender, dtype: str

In [16]:
type(df['gender'].mode())

pandas.Series

In [17]:
df['gender'].mode()[0]

'M'

In [19]:
type(df['gender'].mode()[0])

str

In [20]:
# 인코딩 (Encoding)
# 문자 데이터를 숫자로 바꾸는 과정

In [21]:
# Label Encoding (레이블 인코딩)
# 값에 숫자를 직접 매기는 것.

In [22]:
df['gender_num'] = df['gender'].map({'F':0, 'M':1})

In [23]:
df

   height  weight  age gender  gender_num
0   165.0      55   25      F           0
1   172.0      70   30      M           1
2     NaN      65   28      M           1
3   180.0      80   35      M           1
4   158.0      50   22      F           0
5   175.0      68   29      M           1

In [24]:
# One-Hot Encoding (원-핫 인코딩)
# True / False
# 1 / 0

In [25]:
df_encoded = pd.get_dummies(df, columns=['gender'])

In [26]:
df_encoded

   height  weight  age  gender_num  gender_F  gender_M
0   165.0      55   25           0      True     False
1   172.0      70   30           1     False      True
2     NaN      65   28           1     False      True
3   180.0      80   35           1     False      True
4   158.0      50   22           0      True     False
5   175.0      68   29           1     False      True

In [27]:
# 스케일링
# 숫자 값의 범위를 조정
# ex. 나이 --> 20~70, 연봉 --> 30,000,000
# (숫자를 비슷하게 조정해주는것)

In [28]:
# MinMaScaler
# 사이킷런 안에 있다.
# 값을 0 ~ 1 범위로 바꾸어준다.

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['height_scaled']] = scaler.fit_transform(df[['height']])

In [30]:
df

   height  weight  age gender  gender_num  height_scaled
0   165.0      55   25      F           0       0.318182
1   172.0      70   30      M           1       0.636364
2     NaN      65   28      M           1            NaN
3   180.0      80   35      M           1       1.000000
4   158.0      50   22      F           0       0.000000
5   175.0      68   29      M           1       0.772727

In [31]:
# StandardScaler
# 평균이 0, 표준편차가 1이 되도록 조정
# 사이킷러 안에 있다.

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['height_standard']] = scaler.fit_transform(df[['height']])

In [33]:
df

   height  weight  age gender  gender_num  height_scaled  height_standard
0   165.0      55   25      F           0       0.318182        -0.647660
1   172.0      70   30      M           1       0.636364         0.259064
2     NaN      65   28      M           1            NaN              NaN
3   180.0      80   35      M           1       1.000000         1.295319
4   158.0      50   22      F           0       0.000000        -1.554383
5   175.0      68   29      M           1       0.772727         0.647660