In [ ]:
# 공부시간으로 시험점수 예측 --> 선형 회귀 모델
# 선형 회귀 (Linear Regression)

In [2]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [7]:
np.random.seed(42)

# 예제 데이터 만들기
study_hours = np.random.uniform(1, 10, 100)
scores = study_hours * 8 + np.random.normal(0, 5, 100)

df = pd.DataFrame({
    'study_hours':study_hours,
    'score':scores
})

In [8]:
df.head()

   study_hours      score
0     4.370861  35.402124
1     9.556429  74.956393
2     7.587945  61.162368
3     6.387926  41.165566
4     2.404168  18.134983

In [9]:
df.shape # 데이터 크기

(100, 2)

In [10]:
# Feature(입력값)와 Label(정답) 분리
# 입력 --> X
# 정답 --> Y

In [ ]:
X = df[['study_hours']] # Feature
y = df['score'] # Label

In [12]:
X.head()

   study_hours
0     4.370861
1     9.556429
2     7.587945
3     6.387926
4     2.404168

In [ ]:
y.head()

0    35.402124
1    74.956393
2    61.162368
3    41.165566
4    18.134983
Name: score, dtype: float64

In [14]:
# 학습(train) 데이터와 테스트(test)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 1), (20, 1), (80,), (20,))

In [18]:
# 모델 선택, 학습

In [19]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.coef_ # 기울기

array([7.77702629])

In [ ]:
model.intercept_ # 절편

np.float64(0.9375403112036409)

In [22]:
# 예측 --> predict()

In [23]:
y_pred = model.predict(X_test)

In [24]:
# 평가 
# MAE
# MSE
# RMSE
# R2 score --> 1에 가까울수록 좋다

In [27]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

mse = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [28]:
# mse
mse

2.956712889594886

In [29]:
print(f'mse " {mse:.2f}') # 소수 둘째자리까지

mse " 2.96

In [30]:
r2

0.965918450989329

In [31]:
print(f'r2 score : {r2:2f}') # 1에 가까울수록 잘 만들어진 모델

r2 score : 0.965918

In [32]:
# 새 데이터를 가지고 모델 예측

In [33]:
new_data = pd.DataFrame({
    'study_hours':[5]
})

In [34]:
pred = model.predict(new_data)

In [35]:
pred

array([39.82267174])

In [36]:
pred[0]

np.float64(39.82267174164962)

In [37]:
print(f'5시간 공부했을 때 예상 점수 : {pred[0]:.1f}점')

5시간 공부했을 때 예상 점수 : 39.8점

In [40]:
new_data2 = pd.DataFrame({
    'study_hours':[12]
})
pred2 = model.predict(new_data2)
print(f'12시간 공부했을 때 예상 점수 : {pred2[0]:.1f}점')

12시간 공부했을 때 예상 점수 : 94.3점